
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Feb 08 2024 12:21:15 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Button extends ContentItem {
    public name!: Elements.TextElement;
    public link!: Elements.TextElement;
    public target!: Elements.NumberElement;
}
