
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Clients extends ContentItem {
    public name!: Elements.TextElement;
    public logo!: Elements.AssetsElement;
    public websiteLink!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'website_link') {
                    return 'websiteLink';
                }
                return elementName;
            })
        });
    }
}
