
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Dec 06 2023 14:38:25 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Footer extends ContentItem {
    public heading!: Elements.TextElement;
    public address!: Elements.TextElement;
    public footerImage!: Elements.AssetsElement;
    public footerTrendLabel!: Elements.TextElement;
    public footerTrendHeading!: Elements.TextElement;
    public logo!: Elements.AssetsElement;
    public content!: Elements.TextElement;
    public email!: Elements.TextElement;
    public contactNo!: Elements.TextElement;
    public instagramLink!: Elements.TextElement;
    public linkedinLink!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'footer_image') {
                    return 'footerImage';
                }
                if (elementName === 'footer_trend_label') {
                    return 'footerTrendLabel';
                }
                if (elementName === 'footer_trend_heading') {
                    return 'footerTrendHeading';
                }
                if (elementName === 'contact_no') {
                    return 'contactNo';
                }
                if (elementName === 'instagram_link') {
                    return 'instagramLink';
                }
                if (elementName === 'linkedin_link') {
                    return 'linkedinLink';
                }
                return elementName;
            })
        });
    }
}
