
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Home extends ContentItem {
    public pageTitle!: Elements.TextElement;
    public bannerHeading!: Elements.TextElement;
    public bannerBtnLocale!: Elements.TextElement;
    public bannerBtnLink!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
    public bannerStats!: Elements.LinkedItemsElement<ContentItem>;
    public homeAbout!: Elements.LinkedItemsElement<ContentItem>;
    public services!: Elements.LinkedItemsElement<ContentItem>;
    public heroProjectHeading!: Elements.TextElement;
    public heroProjectContent!: Elements.RichTextElement;
    public heroProjectYoutubeLink!: Elements.TextElement;
    public eventitem!: Elements.LinkedItemsElement<ContentItem>;
    public ourClients!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'banner_heading') {
                    return 'bannerHeading';
                }
                if (elementName === 'banner_btn_locale') {
                    return 'bannerBtnLocale';
                }
                if (elementName === 'banner_btn_link') {
                    return 'bannerBtnLink';
                }
                if (elementName === 'banner_stats') {
                    return 'bannerStats';
                }
                if (elementName === 'home_about') {
                    return 'homeAbout';
                }
                if (elementName === 'hero_project_heading') {
                    return 'heroProjectHeading';
                }
                if (elementName === 'hero_project_content') {
                    return 'heroProjectContent';
                }
                if (elementName === 'hero_project_youtube_link') {
                    return 'heroProjectYoutubeLink';
                }
                if (elementName === 'our_clients') {
                    return 'ourClients';
                }
                return elementName;
            })
        });
    }
}
