
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Feb 09 2024 16:43:58 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homerevamp extends ContentItem {
    public pageTitle!: Elements.TextElement;
    public metaTitle!: Elements.TextElement;
    public metaDescription!: Elements.TextElement;
    public bannerHeading!: Elements.TextElement;
    public bannerContent!: Elements.TextElement;
    public bannerImage!: Elements.AssetsElement;
    public bannerBtnLocale!: Elements.TextElement;
    public bannerBtnLink!: Elements.TextElement;
    public bannerBtnTarget!: Elements.NumberElement;
    public bannerTabs!: Elements.LinkedItemsElement<ContentItem>;
    public stats!: Elements.LinkedItemsElement<ContentItem>;
    public projectsSection!: Elements.LinkedItemsElement<ContentItem>;
    public advertiseBannerOne!: Elements.LinkedItemsElement<ContentItem>;
    public advertiseBannerTwo!: Elements.LinkedItemsElement<ContentItem>;
    public galleryLabel!: Elements.TextElement;
    public galleryHeading!: Elements.TextElement;
    public galleryImages!: Elements.AssetsElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                if (elementName === 'banner_heading') {
                    return 'bannerHeading';
                }
                if (elementName === 'banner_content') {
                    return 'bannerContent';
                }
                if (elementName === 'banner_image') {
                    return 'bannerImage';
                }
                if (elementName === 'banner_btn_locale') {
                    return 'bannerBtnLocale';
                }
                if (elementName === 'banner_btn_link') {
                    return 'bannerBtnLink';
                }
                if (elementName === 'banner_btn_target') {
                    return 'bannerBtnTarget';
                }
                if (elementName === 'banner_tabs') {
                    return 'bannerTabs';
                }
                if (elementName === 'projects_section') {
                    return 'projectsSection';
                }
                if (elementName === 'advertise_banner_one') {
                    return 'advertiseBannerOne';
                }
                if (elementName === 'advertise_banner_two') {
                    return 'advertiseBannerTwo';
                }
                if (elementName === 'gallery_label') {
                    return 'galleryLabel';
                }
                if (elementName === 'gallery_heading') {
                    return 'galleryHeading';
                }
                if (elementName === 'gallery_images') {
                    return 'galleryImages';
                }
                return elementName;
            })
        });
    }
}
