
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Dec 06 2023 13:09:02 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homeadvertise extends ContentItem {
    public image!: Elements.AssetsElement;
    public heading!: Elements.RichTextElement;
}
