
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Feb 08 2024 17:40:05 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class OurServicesItem extends ContentItem {
    public serviceHeading!: Elements.TextElement;
    public serviceImage!: Elements.AssetsElement;
    public link!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'service_heading') {
                    return 'serviceHeading';
                }
                if (elementName === 'service_image') {
                    return 'serviceImage';
                }
                return elementName;
            })
        });
    }
}
