
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Feb 08 2024 17:47:47 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Ourserviceitemrevamp extends ContentItem {
    public name!: Elements.TextElement;
    public images!: Elements.AssetsElement;
    public link!: Elements.TextElement;
}
