
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Feb 09 2024 09:27:43 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Portfolioitems extends ContentItem {
    public name!: Elements.TextElement;
    public image!: Elements.AssetsElement;
}
