
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Services extends ContentItem {
    public itemNumber!: Elements.TextElement;
    public heading!: Elements.TextElement;
    public content!: Elements.TextElement;
    public brief!: Elements.RichTextElement;
    public image!: Elements.AssetsElement;
    public btnLocale!: Elements.TextElement;
    public btnLink!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'item_number') {
                    return 'itemNumber';
                }
                if (elementName === 'btn_locale') {
                    return 'btnLocale';
                }
                if (elementName === 'btn_link') {
                    return 'btnLink';
                }
                return elementName;
            })
        });
    }
}
