
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Feb 08 2024 14:55:45 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Testmymodel extends ContentItem {
    public pageTitle!: Elements.TextElement;
    public metaDescription!: Elements.RichTextElement;
    public metaTitle!: Elements.TextElement;
    public bannerImage!: Elements.TextElement;
    public content!: Elements.TextElement;
    public buttons!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                if (elementName === 'banner_image') {
                    return 'bannerImage';
                }
                return elementName;
            })
        });
    }
}
